name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: jaslr/perplexityvoicesearch/.github/actions/checkout@main
      - name: Setup Pages
        uses: jaslr/perplexityvoicesearch/.github/actions/configure-pages@main
      - name: Upload artifact
        uses: jaslr/perplexityvoicesearch/.github/actions/upload-pages-artifact@main
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: jaslr/perplexityvoicesearch/.github/actions/deploy-pages@main