name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: |
          git clone https://github.com/jaslr/perplexityvoicesearch.git .
          git checkout ${{ github.sha }}

      - name: Setup Pages
        run: |
          echo "Setting up Pages..."
          # Add any necessary setup steps here

      - name: Build project
        run: |
          echo "Building project..."
          # Add your build commands here, if any

      - name: Prepare artifact
        run: |
          echo "Preparing artifact..."
          # Add commands to prepare your artifact
          # For example:
          # zip -r artifact.zip .

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Deploying to GitHub Pages..."
          # Add deployment commands here
          # You might need to use the GitHub CLI or API for this step
          # For example:
          # gh auth login --with-token <<< $GITHUB_TOKEN
          # gh pages deploy --dir .
